"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
OPTIONS = dict(
    argv_emulation=True,
    #frameworks=['libavbin.dylib','pymunk/libchipmunk.dylib'],
    #plist = dict(CFBundleIconFile='gw0rp.icns')
)

setup(
    app=['Splatterboard.py'],
    data_files=[
        'app','pyglet','Resources',
        'Tool Resources', 'Tools', 'Stamps', 'yaml'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
